/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum190625;

/**
 *
 * @author ririn
 */
public class MenuMinuman extends javax.swing.JFrame {

    /**
     * Creates new form MenuMinuman
     */
    private MenuUtama utama;
    public MenuMinuman() {
        initComponents();
    }
    
    public MenuMinuman (MenuUtama utama){
        this.utama = utama;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnReset = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cbAirMineral = new javax.swing.JComboBox<>();
        chkAmericano = new javax.swing.JCheckBox();
        txtTotalMatcha = new javax.swing.JTextField();
        chkMatcha = new javax.swing.JCheckBox();
        txtTotalCappucino = new javax.swing.JTextField();
        chkAirMineral = new javax.swing.JCheckBox();
        txtTotalAmericano = new javax.swing.JTextField();
        txtMatcha = new javax.swing.JTextField();
        txtTotalAirMineral = new javax.swing.JTextField();
        txtCappucino = new javax.swing.JTextField();
        txtAmericano = new javax.swing.JTextField();
        txtAirMineral = new javax.swing.JTextField();
        btnTotalHarga = new javax.swing.JButton();
        cbMatcha = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbCappucino = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtTotalHarga = new javax.swing.JTextField();
        cbAmericano = new javax.swing.JComboBox<>();
        chkCappucino = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setForeground(new java.awt.Color(102, 0, 102));

        btnReset.setBackground(new java.awt.Color(204, 204, 255));
        btnReset.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnReset.setForeground(new java.awt.Color(102, 0, 102));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnReturn.setBackground(new java.awt.Color(204, 204, 255));
        btnReturn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(102, 0, 102));
        btnReturn.setText("Kembali ke Menu Utama");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(211, 211, 211)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(211, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("DAFTAR MENU MINUMAN");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(102, 0, 102));

        cbAirMineral.setBackground(new java.awt.Color(204, 204, 255));
        cbAirMineral.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbAirMineral.setForeground(new java.awt.Color(102, 0, 102));
        cbAirMineral.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbAirMineral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAirMineralActionPerformed(evt);
            }
        });

        chkAmericano.setBackground(new java.awt.Color(204, 204, 255));
        chkAmericano.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        chkAmericano.setForeground(new java.awt.Color(102, 0, 102));
        chkAmericano.setText("Americano");
        chkAmericano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAmericanoActionPerformed(evt);
            }
        });

        txtTotalMatcha.setBackground(new java.awt.Color(204, 204, 255));
        txtTotalMatcha.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTotalMatcha.setForeground(new java.awt.Color(102, 0, 102));
        txtTotalMatcha.setText("0");

        chkMatcha.setBackground(new java.awt.Color(204, 204, 255));
        chkMatcha.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        chkMatcha.setForeground(new java.awt.Color(102, 0, 102));
        chkMatcha.setText("Matcha");
        chkMatcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMatchaActionPerformed(evt);
            }
        });

        txtTotalCappucino.setBackground(new java.awt.Color(204, 204, 255));
        txtTotalCappucino.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTotalCappucino.setForeground(new java.awt.Color(102, 0, 102));
        txtTotalCappucino.setText("0");

        chkAirMineral.setBackground(new java.awt.Color(204, 204, 255));
        chkAirMineral.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        chkAirMineral.setForeground(new java.awt.Color(102, 0, 102));
        chkAirMineral.setText("Air Mineral");
        chkAirMineral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAirMineralActionPerformed(evt);
            }
        });

        txtTotalAmericano.setBackground(new java.awt.Color(204, 204, 255));
        txtTotalAmericano.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTotalAmericano.setForeground(new java.awt.Color(102, 0, 102));
        txtTotalAmericano.setText("0");

        txtMatcha.setBackground(new java.awt.Color(204, 204, 255));
        txtMatcha.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtMatcha.setForeground(new java.awt.Color(102, 0, 102));
        txtMatcha.setText("0");
        txtMatcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatchaActionPerformed(evt);
            }
        });

        txtTotalAirMineral.setBackground(new java.awt.Color(204, 204, 255));
        txtTotalAirMineral.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTotalAirMineral.setForeground(new java.awt.Color(102, 0, 102));
        txtTotalAirMineral.setText("0");

        txtCappucino.setBackground(new java.awt.Color(204, 204, 255));
        txtCappucino.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtCappucino.setForeground(new java.awt.Color(102, 0, 102));
        txtCappucino.setText("0");

        txtAmericano.setBackground(new java.awt.Color(204, 204, 255));
        txtAmericano.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtAmericano.setForeground(new java.awt.Color(102, 0, 102));
        txtAmericano.setText("0");
        txtAmericano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmericanoActionPerformed(evt);
            }
        });

        txtAirMineral.setBackground(new java.awt.Color(204, 204, 255));
        txtAirMineral.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtAirMineral.setForeground(new java.awt.Color(102, 0, 102));
        txtAirMineral.setText("0");

        btnTotalHarga.setBackground(new java.awt.Color(204, 204, 255));
        btnTotalHarga.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnTotalHarga.setForeground(new java.awt.Color(102, 0, 102));
        btnTotalHarga.setText("Total Harga");
        btnTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalHargaActionPerformed(evt);
            }
        });

        cbMatcha.setBackground(new java.awt.Color(204, 204, 255));
        cbMatcha.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbMatcha.setForeground(new java.awt.Color(102, 0, 102));
        cbMatcha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbMatcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMatchaActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("TOTAL");

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("JUMLAH");

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("NAMA");

        cbCappucino.setBackground(new java.awt.Color(204, 204, 255));
        cbCappucino.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbCappucino.setForeground(new java.awt.Color(102, 0, 102));
        cbCappucino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbCappucino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCappucinoActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("HARGA");

        txtTotalHarga.setBackground(new java.awt.Color(204, 204, 255));
        txtTotalHarga.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTotalHarga.setForeground(new java.awt.Color(102, 0, 102));
        txtTotalHarga.setText("0");

        cbAmericano.setBackground(new java.awt.Color(204, 204, 255));
        cbAmericano.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbAmericano.setForeground(new java.awt.Color(102, 0, 102));
        cbAmericano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbAmericano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAmericanoActionPerformed(evt);
            }
        });

        chkCappucino.setBackground(new java.awt.Color(204, 204, 255));
        chkCappucino.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        chkCappucino.setForeground(new java.awt.Color(102, 0, 102));
        chkCappucino.setText("Cappucino");
        chkCappucino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCappucinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(510, Short.MAX_VALUE)
                .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(jLabel4)
                            .addGap(102, 102, 102)
                            .addComponent(jLabel5)
                            .addGap(103, 103, 103)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addGap(32, 32, 32))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(chkMatcha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chkCappucino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chkAmericano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chkAirMineral, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(31, 31, 31)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCappucino, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAmericano, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAirMineral, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMatcha, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(48, 48, 48)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbAmericano, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbCappucino, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbMatcha, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTotalHarga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbAirMineral, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTotalCappucino, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTotalAmericano, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTotalAirMineral, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTotalMatcha, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(21, 21, 21)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(347, Short.MAX_VALUE)
                .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4))
                    .addGap(28, 28, 28)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtTotalAirMineral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(txtTotalAmericano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(txtTotalCappucino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(txtTotalMatcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cbAirMineral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(cbAmericano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(34, 34, 34)
                                    .addComponent(cbCappucino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(38, 38, 38)
                                    .addComponent(cbMatcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(chkAirMineral)
                                        .addComponent(txtAirMineral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(27, 27, 27)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtAmericano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(chkAmericano))
                                    .addGap(32, 32, 32)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(chkCappucino)
                                        .addComponent(txtCappucino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(36, 36, 36)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(chkMatcha)
                                        .addComponent(txtMatcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(48, 48, 48)
                            .addComponent(btnTotalHarga)))
                    .addContainerGap(27, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtAirMineral.setText("0");
        txtAmericano.setText("0");
        txtCappucino.setText("0");
        txtMatcha.setText("0");
        txtTotalHarga.setText("0");
        cbAirMineral.setSelectedIndex(0);
        cbAmericano.setSelectedIndex(0);
        cbCappucino.setSelectedIndex(0);
        cbMatcha.setSelectedIndex(0);
        chkAirMineral.setSelected(false);
        chkAmericano.setSelected(false);
        chkCappucino.setSelected(false);
        chkMatcha.setSelected(false);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        String total = txtTotalHarga.getText();
        utama.setTotalMinuman(total);
        this.dispose();
    }//GEN-LAST:event_btnReturnActionPerformed

    private void cbAirMineralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAirMineralActionPerformed
        int jml = (int) cbAirMineral.getSelectedIndex();
        double harga = Double.parseDouble(txtAirMineral.getText());
        double total = jml*harga;
        txtTotalAirMineral.setText(Double.toString(total));
    }//GEN-LAST:event_cbAirMineralActionPerformed

    private void chkAmericanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAmericanoActionPerformed
        txtAmericano.setText("45000");
    }//GEN-LAST:event_chkAmericanoActionPerformed

    private void chkMatchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMatchaActionPerformed
        txtMatcha.setText("25000");
    }//GEN-LAST:event_chkMatchaActionPerformed

    private void chkAirMineralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAirMineralActionPerformed
        txtAirMineral.setText("100000");
    }//GEN-LAST:event_chkAirMineralActionPerformed

    private void txtMatchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatchaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatchaActionPerformed

    private void txtAmericanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmericanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmericanoActionPerformed

    private void btnTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalHargaActionPerformed
        double airMineral = Double.parseDouble(txtTotalAirMineral.getText());
        double americano = Double.parseDouble(txtTotalAmericano.getText());
        double cappucino = Double.parseDouble(txtTotalCappucino.getText());
        double matcha = Double.parseDouble(txtTotalMatcha.getText());

        double total = airMineral + americano + cappucino + matcha;
        txtTotalHarga.setText(String.valueOf(total));
    }//GEN-LAST:event_btnTotalHargaActionPerformed

    private void cbMatchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMatchaActionPerformed
        int jml = (int) cbMatcha.getSelectedIndex();
        double harga = Double.parseDouble(txtMatcha.getText());
        double total = jml*harga;
        txtTotalMatcha.setText(Double.toString(total));
    }//GEN-LAST:event_cbMatchaActionPerformed

    private void cbCappucinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCappucinoActionPerformed
        int jml = (int) cbCappucino.getSelectedIndex();
        double harga = Double.parseDouble(txtCappucino.getText());
        double total = jml*harga;
        txtTotalCappucino.setText(Double.toString(total));
    }//GEN-LAST:event_cbCappucinoActionPerformed

    private void cbAmericanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAmericanoActionPerformed
        int jml = (int) cbAmericano.getSelectedIndex();
        double harga = Double.parseDouble(txtAmericano.getText());
        double total = jml*harga;
        txtTotalAmericano.setText(Double.toString(total));
    }//GEN-LAST:event_cbAmericanoActionPerformed

    private void chkCappucinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCappucinoActionPerformed
        txtCappucino.setText("45000");
    }//GEN-LAST:event_chkCappucinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMinuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnTotalHarga;
    private javax.swing.JComboBox<String> cbAirMineral;
    private javax.swing.JComboBox<String> cbAmericano;
    private javax.swing.JComboBox<String> cbCappucino;
    private javax.swing.JComboBox<String> cbMatcha;
    private javax.swing.JCheckBox chkAirMineral;
    private javax.swing.JCheckBox chkAmericano;
    private javax.swing.JCheckBox chkCappucino;
    private javax.swing.JCheckBox chkMatcha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAirMineral;
    private javax.swing.JTextField txtAmericano;
    private javax.swing.JTextField txtCappucino;
    private javax.swing.JTextField txtMatcha;
    private javax.swing.JTextField txtTotalAirMineral;
    private javax.swing.JTextField txtTotalAmericano;
    private javax.swing.JTextField txtTotalCappucino;
    private javax.swing.JTextField txtTotalHarga;
    private javax.swing.JTextField txtTotalMatcha;
    // End of variables declaration//GEN-END:variables
}
