/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum190625;

import javax.swing.JOptionPane;

/**
 *
 * @author ririn
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelNamaPelanggan = new javax.swing.JLabel();
        labelNoMeja = new javax.swing.JLabel();
        txtNoMeja = new javax.swing.JTextField();
        txtNamaPelanggan = new javax.swing.JTextField();
        btnTotal = new javax.swing.JButton();
        btnDaftarMinuman = new javax.swing.JButton();
        btnDaftarMakanan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelTotalMakanan = new javax.swing.JLabel();
        labelTotalMinuman = new javax.swing.JLabel();
        labelPajak = new javax.swing.JLabel();
        labelTotalHarga = new javax.swing.JLabel();
        labelTotalBayar = new javax.swing.JLabel();
        txtTotalHarga = new javax.swing.JTextField();
        txtTotalMinuman = new javax.swing.JTextField();
        txtTotalMakanan = new javax.swing.JTextField();
        txtPajak = new javax.swing.JTextField();
        txtTotalBayar = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUang = new javax.swing.JTextField();
        btnHitungKembalian = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnKeluar = new javax.swing.JButton();
        btnSelesai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setText("FORM PEMESANAN  KANTIN XYZ");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setForeground(new java.awt.Color(255, 51, 153));

        labelNamaPelanggan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labelNamaPelanggan.setForeground(new java.awt.Color(102, 102, 0));
        labelNamaPelanggan.setText("Nama Pelanggan");

        labelNoMeja.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labelNoMeja.setForeground(new java.awt.Color(102, 102, 0));
        labelNoMeja.setText("No Meja");

        txtNoMeja.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtNoMeja.setForeground(new java.awt.Color(102, 102, 0));

        txtNamaPelanggan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtNamaPelanggan.setForeground(new java.awt.Color(102, 102, 0));

        btnTotal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnTotal.setForeground(new java.awt.Color(102, 102, 0));
        btnTotal.setText("Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        btnDaftarMinuman.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnDaftarMinuman.setForeground(new java.awt.Color(102, 102, 0));
        btnDaftarMinuman.setText("Daftar Minuman");
        btnDaftarMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarMinumanActionPerformed(evt);
            }
        });

        btnDaftarMakanan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnDaftarMakanan.setForeground(new java.awt.Color(102, 102, 0));
        btnDaftarMakanan.setText("Daftar Makanan");
        btnDaftarMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarMakananActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNoMeja)
                    .addComponent(labelNamaPelanggan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(txtNoMeja))
                .addGap(41, 41, 41))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnDaftarMinuman)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(139, 139, 139)
                            .addComponent(btnDaftarMakanan)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(btnTotal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNamaPelanggan)
                    .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNoMeja)
                    .addComponent(txtNoMeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(btnDaftarMakanan)
                .addGap(32, 32, 32)
                .addComponent(btnDaftarMinuman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnTotal)
                .addGap(25, 25, 25))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setForeground(new java.awt.Color(255, 51, 153));

        labelTotalMakanan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labelTotalMakanan.setForeground(new java.awt.Color(102, 102, 0));
        labelTotalMakanan.setText("Total Makanan");

        labelTotalMinuman.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labelTotalMinuman.setForeground(new java.awt.Color(102, 102, 0));
        labelTotalMinuman.setText("Total Minuman");

        labelPajak.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labelPajak.setForeground(new java.awt.Color(102, 102, 0));
        labelPajak.setText("Pajak 10%");

        labelTotalHarga.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labelTotalHarga.setForeground(new java.awt.Color(102, 102, 0));
        labelTotalHarga.setText("Total Harga");

        labelTotalBayar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labelTotalBayar.setForeground(new java.awt.Color(102, 102, 0));
        labelTotalBayar.setText("Total Bayar");

        txtTotalHarga.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTotalHarga.setForeground(new java.awt.Color(102, 102, 0));

        txtTotalMinuman.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTotalMinuman.setForeground(new java.awt.Color(102, 102, 0));
        txtTotalMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalMinumanActionPerformed(evt);
            }
        });

        txtTotalMakanan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTotalMakanan.setForeground(new java.awt.Color(102, 102, 0));

        txtPajak.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtPajak.setForeground(new java.awt.Color(102, 102, 0));
        txtPajak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPajakActionPerformed(evt);
            }
        });

        txtTotalBayar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTotalBayar.setForeground(new java.awt.Color(102, 102, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTotalMinuman)
                    .addComponent(labelTotalMakanan)
                    .addComponent(labelTotalHarga)
                    .addComponent(labelPajak)
                    .addComponent(labelTotalBayar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTotalMakanan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(txtTotalMinuman, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTotalHarga, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPajak, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTotalBayar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalMakanan)
                    .addComponent(txtTotalMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalMinuman)
                    .addComponent(txtTotalMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalHarga)
                    .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPajak)
                    .addComponent(txtPajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalBayar)
                    .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setForeground(new java.awt.Color(255, 51, 153));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 0));
        jLabel2.setText("Total Uang");

        txtUang.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtUang.setForeground(new java.awt.Color(102, 102, 0));

        btnHitungKembalian.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnHitungKembalian.setForeground(new java.awt.Color(102, 102, 0));
        btnHitungKembalian.setText("Hitung Kembalian");
        btnHitungKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungKembalianActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 0));
        jLabel3.setText("Total Kembalian");

        txtKembalian.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtKembalian.setForeground(new java.awt.Color(102, 102, 0));
        txtKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKembalianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtUang, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHitungKembalian)
                .addGap(73, 73, 73))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHitungKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setForeground(new java.awt.Color(255, 51, 153));

        btnKeluar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(102, 102, 0));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnSelesai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSelesai.setForeground(new java.awt.Color(102, 102, 0));
        btnSelesai.setText("Selesai");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(btnSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        if (txtNamaPelanggan.getText().isEmpty() || txtNoMeja.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nama Pelanggan dan No Meja harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    Double makanan = Double.parseDouble(txtTotalMakanan.getText());
    Double minuman = Double.parseDouble(txtTotalMinuman.getText());
    Double total = makanan + minuman;
    Double pajak = 0.1 * total;
    Double bayar = total + pajak;
    txtTotalBayar.setText(Double.toString(bayar));
    txtPajak.setText(Double.toString(pajak));
    txtTotalHarga.setText(Double.toString(total));
        
    }//GEN-LAST:event_btnTotalActionPerformed

    public void setTotalMakanan(String nilai){
        txtTotalMakanan.setText(nilai);
    }
    public void setTotalMinuman(String nilai){
        txtTotalMinuman.setText(nilai);
    }
    
    private void btnDaftarMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarMinumanActionPerformed
        if (txtNamaPelanggan.getText().isEmpty() || txtNoMeja.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nama Pelanggan dan No Meja harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    MenuMinuman form = new MenuMinuman(this);
    form.setVisible(true);
    }//GEN-LAST:event_btnDaftarMinumanActionPerformed

    private void btnDaftarMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarMakananActionPerformed
        if (txtNamaPelanggan.getText().isEmpty() || txtNoMeja.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nama Pelanggan dan No Meja harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    MenuMakanan form = new MenuMakanan(this);
    form.setVisible(true);
    }//GEN-LAST:event_btnDaftarMakananActionPerformed

    private void txtTotalMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalMinumanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalMinumanActionPerformed

    private void txtPajakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPajakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPajakActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        if (txtNamaPelanggan.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nama Pelanggan harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
        }
        String message = "Pelanggan " + txtNamaPelanggan.getText() 
                   + " telah selesai berbelanja.\n"
                   + "Total Bayar: " + txtTotalBayar.getText();
    
        JOptionPane.showMessageDialog(this, message, "Transaksi Selesai", JOptionPane.INFORMATION_MESSAGE);
        txtNamaPelanggan.setText("");
        txtNoMeja.setText("");
        txtTotalMakanan.setText("0");
        txtTotalMinuman.setText("0");
        txtTotalHarga.setText("0");
        txtPajak.setText("0");
        txtTotalBayar.setText("0");
        txtUang.setText("");
        txtKembalian.setText("");
    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void txtKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKembalianActionPerformed

    private void btnHitungKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungKembalianActionPerformed
        Double bayar = Double.parseDouble(txtTotalBayar.getText());
        Double uang = Double.parseDouble(txtUang.getText());
        if(uang<bayar){
            JOptionPane.showMessageDialog(this, "Uang Anda Kurang", "Peringatan", JOptionPane.WARNING_MESSAGE);
            txtUang.requestFocus();
        } else{
            Double kembalian = uang - bayar;
            txtKembalian.setText(Double.toString(kembalian));
        }
    }//GEN-LAST:event_btnHitungKembalianActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int confirm = JOptionPane.showConfirmDialog(
                    null, 
                    "Apakah Anda yakin ingin keluar?", 
                    "Konfirmasi Keluar", 
                    JOptionPane.YES_NO_OPTION
                );
                if (confirm == JOptionPane.YES_OPTION) {
                    System.exit(0);
                }
            }
        });
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaftarMakanan;
    private javax.swing.JButton btnDaftarMinuman;
    private javax.swing.JButton btnHitungKembalian;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JButton btnTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelNamaPelanggan;
    private javax.swing.JLabel labelNoMeja;
    private javax.swing.JLabel labelPajak;
    private javax.swing.JLabel labelTotalBayar;
    private javax.swing.JLabel labelTotalHarga;
    private javax.swing.JLabel labelTotalMakanan;
    private javax.swing.JLabel labelTotalMinuman;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtNamaPelanggan;
    private javax.swing.JTextField txtNoMeja;
    private javax.swing.JTextField txtPajak;
    private javax.swing.JTextField txtTotalBayar;
    private javax.swing.JTextField txtTotalHarga;
    private javax.swing.JTextField txtTotalMakanan;
    private javax.swing.JTextField txtTotalMinuman;
    private javax.swing.JTextField txtUang;
    // End of variables declaration//GEN-END:variables
}
