/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tugas260625;

import javax.swing.JOptionPane;

/**
 *
 * @author ririn
 */
public class MenuUtama extends javax.swing.JFrame {
    private String username = "demo";
    /**
     * Creates new form MenuUtama
     */
    public MenuUtama(String username) {
        initComponents();
        this.username = username;
        setLocationRelativeTo(null);
        labelJudul.setText("SELAMAT DATANG, " + username.toUpperCase() + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelJudul = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCekSaldo = new javax.swing.JButton();
        btnTarikTunai = new javax.swing.JButton();
        btnTransfer = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnTambahSaldo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelBahasa = new javax.swing.JLabel();
        cbBahasa = new javax.swing.JComboBox<>();
        btnBantuan = new javax.swing.JButton();
        labelJudul1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelJudul.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelJudul.setText("SELAMAT DATANG, PENGGUNA!");

        btnCekSaldo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnCekSaldo.setText("1. [CEK SALDO]");
        btnCekSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekSaldoActionPerformed(evt);
            }
        });

        btnTarikTunai.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnTarikTunai.setText("2. [TARIK TUNAI]");
        btnTarikTunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarikTunaiActionPerformed(evt);
            }
        });

        btnTransfer.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnTransfer.setText("3. [TRANSFER]");
        btnTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferActionPerformed(evt);
            }
        });

        btnKeluar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnKeluar.setText("4. [KELUAR]");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnTambahSaldo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnTambahSaldo.setText("4. [TAMBAH SALDO]");
        btnTambahSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTambahSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(btnTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTarikTunai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCekSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(btnCekSaldo)
                .addGap(18, 18, 18)
                .addComponent(btnTarikTunai)
                .addGap(18, 18, 18)
                .addComponent(btnTransfer)
                .addGap(18, 18, 18)
                .addComponent(btnTambahSaldo)
                .addGap(18, 18, 18)
                .addComponent(btnKeluar))
        );

        labelBahasa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        labelBahasa.setText("BAHASA");

        cbBahasa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cbBahasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDONESIA", "INGGRIS" }));
        cbBahasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBahasaActionPerformed(evt);
            }
        });

        btnBantuan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnBantuan.setText("[BANTUAN]");
        btnBantuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBantuanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBahasa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbBahasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnBantuan))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBahasa)
                    .addComponent(cbBahasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBantuan))
                .addContainerGap())
        );

        labelJudul1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelJudul1.setText("MENU UTAMA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelJudul1)
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelJudul, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(101, 101, 101))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(labelJudul)
                .addGap(18, 18, 18)
                .addComponent(labelJudul1)
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCekSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekSaldoActionPerformed
         JOptionPane.showMessageDialog(this, 
        "Saldo Anda: Rp " + String.format("%,.2f", Saldo.getSaldo()), 
        "Cek Saldo - " + username, 
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnCekSaldoActionPerformed

    private void btnTarikTunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarikTunaiActionPerformed
       this.dispose(); 
       new TarikTunai(username).setVisible(true);
    }//GEN-LAST:event_btnTarikTunaiActionPerformed

    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferActionPerformed
        this.dispose(); 
        new Transfer(username).setVisible(true);
    }//GEN-LAST:event_btnTransferActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
            this, 
            "Apakah Anda yakin ingin keluar?", 
            "Konfirmasi Keluar", 
            JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void cbBahasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBahasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBahasaActionPerformed

    private void btnBantuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBantuanActionPerformed
        String message = "Aplikasi Simulasi ATM\n" +
                       "1. Cek Saldo - Melihat saldo akun Anda\n" +
                       "2. Tarik Tunai - Menarik uang dari akun Anda\n" +
                       "3. Transfer - Transfer uang ke akun lain\n" +
                       "4. Tambah Saldo - Menambah saldo untuk akun Anda\n" +
                       "5. Keluar - Keluar dari aplikasi";
                       
            
        JOptionPane.showMessageDialog(this, message, "Informasi Bantuan", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnBantuanActionPerformed

    private void btnTambahSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahSaldoActionPerformed
        this.dispose(); 
        new TambahSaldo(username).setVisible(true);
    }//GEN-LAST:event_btnTambahSaldoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama("demo").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBantuan;
    private javax.swing.JButton btnCekSaldo;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnTambahSaldo;
    private javax.swing.JButton btnTarikTunai;
    private javax.swing.JButton btnTransfer;
    private javax.swing.JComboBox<String> cbBahasa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelBahasa;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelJudul1;
    // End of variables declaration//GEN-END:variables
}
