/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tugas260625;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author ririn
 */
public class TarikTunai extends javax.swing.JFrame {

    private String username;
    private int saldo = 1000000;
    /**
     * Creates new form TarikTunai
     */
    public TarikTunai(String username) {
        initComponents();
        this.username = username;

        ButtonGroup group = new ButtonGroup();
        group.add(rbLimaPuluh);
        group.add(rbSeratus);
        group.add(rbDuaRatus);
        group.add(rbLimaRatus);

        txtJumlahLain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtJumlahLainMouseClicked(evt);
            }
        });

        setLocationRelativeTo(null);
    }

    private void txtJumlahLainMouseClicked(java.awt.event.MouseEvent evt) {
    if (!txtJumlahLain.isEnabled()) {
        txtJumlahLain.setEnabled(true);
        txtJumlahLain.requestFocus();
        
        ButtonGroup group = new ButtonGroup();
        group.add(rbLimaPuluh);
        group.add(rbSeratus);
        group.add(rbDuaRatus);
        group.add(rbLimaRatus);
        group.clearSelection();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnKeluar = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        labelJudul = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelPilih = new javax.swing.JLabel();
        rbSeratus = new javax.swing.JRadioButton();
        rbLimaPuluh = new javax.swing.JRadioButton();
        rbDuaRatus = new javax.swing.JRadioButton();
        rbLimaRatus = new javax.swing.JRadioButton();
        labelJumlah = new javax.swing.JLabel();
        txtJumlahLain = new javax.swing.JTextField();
        btnTarik = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnKeluar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnKeluar.setText("KELUAR");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnKembali.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnKembali.setText("KEMBALI");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKembali)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKeluar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembali)
                    .addComponent(btnKeluar))
                .addContainerGap())
        );

        labelJudul.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelJudul.setText("TARIK TUNAI");

        labelPilih.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        labelPilih.setText("PILIH JUMLAH");

        rbSeratus.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rbSeratus.setText("100000");
        rbSeratus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSeratusActionPerformed(evt);
            }
        });

        rbLimaPuluh.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rbLimaPuluh.setText("50000");
        rbLimaPuluh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLimaPuluhActionPerformed(evt);
            }
        });

        rbDuaRatus.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rbDuaRatus.setText("200000");
        rbDuaRatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDuaRatusActionPerformed(evt);
            }
        });

        rbLimaRatus.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rbLimaRatus.setText("500000");
        rbLimaRatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLimaRatusActionPerformed(evt);
            }
        });

        labelJumlah.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        labelJumlah.setText("MASUKKAN JUMLAH LAIN");

        txtJumlahLain.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtJumlahLain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahLainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbSeratus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbLimaRatus))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(labelJumlah)
                                .addGap(18, 18, 18)
                                .addComponent(txtJumlahLain, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelPilih)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(rbLimaPuluh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbDuaRatus)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPilih)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbLimaPuluh)
                    .addComponent(rbDuaRatus))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSeratus)
                    .addComponent(rbLimaRatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJumlah)
                    .addComponent(txtJumlahLain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnTarik.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnTarik.setText("TARIK");
        btnTarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnTarik)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelJudul)
                        .addGap(199, 199, 199))))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(labelJudul)
                .addGap(74, 74, 74)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTarik)
                .addGap(48, 48, 48)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        this.dispose();
    new MenuUtama(username).setVisible(true);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda yakin ingin keluar?",
            "Konfirmasi Keluar",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0); 
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void rbLimaPuluhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLimaPuluhActionPerformed
        txtJumlahLain.setEnabled(false);
        txtJumlahLain.setText("");
    }//GEN-LAST:event_rbLimaPuluhActionPerformed

    private void rbSeratusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSeratusActionPerformed
        txtJumlahLain.setEnabled(false);
        txtJumlahLain.setText("");
    }//GEN-LAST:event_rbSeratusActionPerformed

    private void rbDuaRatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDuaRatusActionPerformed
        txtJumlahLain.setEnabled(false);
        txtJumlahLain.setText("");
    }//GEN-LAST:event_rbDuaRatusActionPerformed

    private void rbLimaRatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLimaRatusActionPerformed
        txtJumlahLain.setEnabled(false);
        txtJumlahLain.setText("");
    }//GEN-LAST:event_rbLimaRatusActionPerformed

    private void txtJumlahLainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahLainActionPerformed
        if (!txtJumlahLain.isEnabled()) {
            txtJumlahLain.setEnabled(true);
            
            ButtonGroup group = new ButtonGroup();
            group.add(rbLimaPuluh);
            group.add(rbSeratus);
            group.add(rbDuaRatus);
            group.add(rbLimaRatus);
            group.clearSelection();
        }
    }//GEN-LAST:event_txtJumlahLainActionPerformed

    private void btnTarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarikActionPerformed
        int jumlahTarik = 0;
        boolean isCustomAmount = false;
        
        if (rbLimaPuluh.isSelected()) {
            jumlahTarik = 50000;
        } else if (rbSeratus.isSelected()) {
            jumlahTarik = 100000;
        } else if (rbDuaRatus.isSelected()) {
            jumlahTarik = 200000;
        } else if (rbLimaRatus.isSelected()) {
            jumlahTarik = 500000;
        } else if (txtJumlahLain.isEnabled() && !txtJumlahLain.getText().isEmpty()) {
            try {
                jumlahTarik = Integer.parseInt(txtJumlahLain.getText());
                if (jumlahTarik <= 0) {
                    JOptionPane.showMessageDialog(this, "Jumlah harus lebih dari 0", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                isCustomAmount = true;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Masukkan jumlah yang valid", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih jumlah atau masukkan jumlah lain", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (jumlahTarik > saldo) {
            JOptionPane.showMessageDialog(this, "Saldo tidak mencukupi", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (jumlahTarik % 50000 != 0) {
            JOptionPane.showMessageDialog(this, "Jumlah harus kelipatan 50.000", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        saldo -= jumlahTarik;
        
        JOptionPane.showMessageDialog(this, 
            "Penarikan berhasil!\nJumlah: Rp " + String.format("%,d", jumlahTarik) + 
            "\nSaldo tersisa: Rp " + String.format("%,d", saldo), 
            "Success", 
            JOptionPane.INFORMATION_MESSAGE);
        
        ButtonGroup group = new ButtonGroup();
        group.add(rbLimaPuluh);
        group.add(rbSeratus);
        group.add(rbDuaRatus);
        group.add(rbLimaRatus);
        group.clearSelection();
        txtJumlahLain.setText("");
        txtJumlahLain.setEnabled(false);
    }//GEN-LAST:event_btnTarikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TarikTunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TarikTunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TarikTunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TarikTunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TarikTunai("demo").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTarik;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelJumlah;
    private javax.swing.JLabel labelPilih;
    private javax.swing.JRadioButton rbDuaRatus;
    private javax.swing.JRadioButton rbLimaPuluh;
    private javax.swing.JRadioButton rbLimaRatus;
    private javax.swing.JRadioButton rbSeratus;
    private javax.swing.JTextField txtJumlahLain;
    // End of variables declaration//GEN-END:variables
}
