/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum12062025;

import javax.swing.JOptionPane;

/**
 *
 * @author ririn
 */
public class PolaPerulangan extends javax.swing.JFrame {

    /**
     * Creates new form PolaPerulangan
     */
    public PolaPerulangan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAngka1 = new javax.swing.JLabel();
        labelJudul = new javax.swing.JLabel();
        labelAngka2 = new javax.swing.JLabel();
        cbPilihPola = new javax.swing.JComboBox<>();
        labelPilihPola = new javax.swing.JLabel();
        btnProses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaHasil = new javax.swing.JTextArea();
        txtAngka1 = new javax.swing.JTextField();
        txtAngka2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelAngka1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelAngka1.setText("Masukkan Angka 1");

        labelJudul.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelJudul.setText("POLA PERULANGAN");

        labelAngka2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelAngka2.setText("Masukkan Angka 2");

        cbPilihPola.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbPilihPola.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Pola", "Pola 1", "Pola 2", "Pola 3", "Pola 4", "Pola 5", "Pola 6", "Pola 7", " " }));
        cbPilihPola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPilihPolaActionPerformed(evt);
            }
        });

        labelPilihPola.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelPilihPola.setText("Pilih Pola");

        btnProses.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        areaHasil.setColumns(20);
        areaHasil.setRows(5);
        jScrollPane1.setViewportView(areaHasil);

        txtAngka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAngka2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelAngka2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAngka1)
                    .addComponent(labelPilihPola, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtAngka2)
                    .addComponent(cbPilihPola, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAngka1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProses)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(labelJudul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelJudul)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAngka1)
                    .addComponent(txtAngka1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelAngka2)
                    .addComponent(txtAngka2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPilihPola)
                    .addComponent(cbPilihPola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProses))
                .addGap(71, 71, 71)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbPilihPolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPilihPolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPilihPolaActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
                                                 
    try {
        int a = Integer.parseInt(txtAngka1.getText());
        int b = Integer.parseInt(txtAngka2.getText());
        int pil = cbPilihPola.getSelectedIndex();
        StringBuilder pola = new StringBuilder("Tampilan Pola\n\n");
        
        switch(pil) {
            case 1: 
                for(int i=1; i<=a; i++) {
                    for(int j=1; j<=b; j++) {
                        pola.append(" * ");
                    }
                    pola.append("\n");
                }
                break;
                
            case 2: 
                for(int i=1; i<=a; i++) {
                    for(int j=1; j<=b; j++) {
                        pola.append((i+j)%2 == 0 ? "X " : "O ");
                    }
                    pola.append("\n");
                }
                break;
                
            case 3: 
                for(int i=1; i<=a; i++) {
                    for(int j=1; j<=i; j++) {
                        pola.append(" * ");
                    }
                    pola.append("\n");
                }
                break;
                
            case 4: 
                for(int i=1; i<=a; i++) {
                    for(int j=1; j<=a-i; j++) {
                        pola.append("   ");
                    }
                    for(int j=1; j<=i; j++) {
                        pola.append(" * ");
                    }
                    pola.append("\n");
                }
                break;
                
            case 5: 
                for(int i=1; i<=a; i++) {
                    for(int j=1; j<=a-i; j++) {
                        pola.append("   ");
                    }
                    for(int j=1; j<=2*i-1; j++) {
                        pola.append(" * ");
                    }
                    pola.append("\n");
                }
                break;
                
            case 6: 
                for(int i=1; i<=a; i++) {
                    for(int j=1; j<=a; j++) {
                        pola.append((i==j || i+j==a+1) ? " * " : "   ");
                    }
                    pola.append("\n");
                }
                break;
                
            case 7: 
                for(int i=1; i<=a; i++) {
                    for(int j=1; j<=b; j++) {
                        pola.append((i==1 || i==a || j==1 || j==b) ? " * " : "   ");
                    }
                    pola.append("\n");
                }
                break;
                
            default:
                pola.append("Pilih pola yang valid (1-7)");
        }
        
        areaHasil.setText(pola.toString());
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, 
            "Input harus berupa angka bulat", 
            "Error Input", 
            JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnProsesActionPerformed

    private void txtAngka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAngka2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAngka2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolaPerulangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PolaPerulangan().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaHasil;
    private javax.swing.JButton btnProses;
    private javax.swing.JComboBox<String> cbPilihPola;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAngka1;
    private javax.swing.JLabel labelAngka2;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelPilihPola;
    private javax.swing.JTextField txtAngka1;
    private javax.swing.JTextField txtAngka2;
    // End of variables declaration//GEN-END:variables
}
